version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"
  #secrets-manager:
     # key: secret-id:json-key:version-stage:version-id
     # key: secret-id:json-key:version-stage:version-id
  #exported-variables:
     # - variable
     # - variable
  #git-credential-helper: yes

phases:
  install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    runtime-vecrsions:
      nodejs: 12
      # name: version
    commands:
        - pip3 install mkdocs-material
        - pip3 install pymdown-extensions
        - pip3 install taskcat
        - apt-get install jq -y
        - npm install -g npm
        - npm install -g grunt-cli
        - npm install
        - find ./website/lambda -type d -exec npm install {} +
        #- apt-get install node-gyp -y --install-suggests
        #- apt-get install npm -y --install-suggests
        # - apt-get install awscli -y --install-suggests
 #pre_build:
    #commands:
      # - command
      # - command
  build:
    commands:
      #- ls
      - grunt deploy-skipinfra --region-us-east-1 --bucket=asamant-123-content-us-east-1 --cfnstack=asamant-123
      # - command
  #post_build:
    #commands:
      # - command
      # - command
#reports:
  #report-name-or-arn:
    #files:
      # - location
      # - location
    #base-directory: location
    #discard-paths: yes
    #file-format: JunitXml | CucumberJson
#artifacts:
  #files:
    # - location
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths